// Standalone multi-page preview. No live gateway, credentials or native execution.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const output=process.argv[2];if(!output)throw Error('Supply the output .html path');
const mini=path.resolve(__dirname,'../../miniprogram');
const pages=JSON.parse(fs.readFileSync(path.join(mini,'app.json'),'utf8')).pages.map(route=>({id:route.split('/')[1],label:JSON.parse(fs.readFileSync(path.join(mini,route+'.json'),'utf8')).navigationBarTitleText||route.split('/')[1]}));
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'weagent-launcher-'));let html;
try{const file=path.join(directory,'current.html');execFileSync(process.execPath,[path.join(__dirname,'build.cjs'),file],{stdio:'inherit'});html=fs.readFileSync(file,'utf8');}finally{fs.rmSync(directory,{recursive:true,force:true});}
const script=`const source=${JSON.stringify(html).replace(/</g,'\\u003c')};const pages=${JSON.stringify(pages)};
const page=document.querySelector('#page'),theme=document.querySelector('#theme'),motion=document.querySelector('#motion'),width=document.querySelector('#width'),frame=document.querySelector('#preview');
for(const p of pages){const o=document.createElement('option');o.value=p.id;o.textContent=p.label;page.append(o);}page.value='session';
function show(){const query='?page='+encodeURIComponent(page.value)+'&theme='+encodeURIComponent(theme.value);const boot='<script>window.__PREVIEW_QUERY='+JSON.stringify(query)+';<'+ '/script>';const end='<script>window.__preview.setMotion('+JSON.stringify(motion.value)+');<'+ '/script>';frame.srcdoc=source.replace('<head>','<head>'+boot).replace('</body>',end+'</body>');document.querySelector('.device').style.width=width.value+'px';document.querySelector('#caption').textContent=pages.find(p=>p.id===page.value).label+' / '+theme.options[theme.selectedIndex].text;}
for(const control of [page,theme,motion,width])control.addEventListener('change',show);show();`;
const text=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>喵连 \u4ea4\u4e92\u9884\u89c8</title><style>
*{box-sizing:border-box}body{margin:0;background:#101210;color:#e9eadf;font:14px system-ui,-apple-system,sans-serif}header{padding:24px 5%;border-bottom:1px solid #30362c;display:flex;gap:22px;justify-content:space-between;align-items:center;flex-wrap:wrap}h1{font-size:22px;margin:0 0 6px}header p{margin:0;color:#a5ad9d;font-size:12px}nav{display:flex;gap:12px;flex-wrap:wrap}label{display:grid;gap:5px;color:#a5ad9d;font-size:11px}select{background:#21251e;color:#e9eadf;border:1px solid #434d3b;border-radius:9px;padding:9px;max-width:180px;min-height:40px}main{padding:26px 12px 40px;display:grid;justify-items:center;gap:14px}.device{box-sizing:content-box;max-width:calc(100% - 2px);border:1px solid #41493a;border-radius:24px;overflow:hidden;box-shadow:0 30px 70px #0006;background:#171815}iframe{width:100%;height:844px;display:block;border:0}#caption{color:#a5ad9d;font-size:12px;margin:0;text-align:center}select:focus-visible{outline:2px solid #b8d093;outline-offset:3px}@media(max-width:600px){header{padding:18px}nav{gap:8px}select{max-width:160px}main{padding-top:18px}}
</style><header><div><h1>喵连 / UI Preview</h1><p>24 \u9875\u9762 \u00b7 \u516d\u5957\u4e3b\u9898 \u00b7 \u79bb\u7ebf\u6f14\u793a\uff0c\u4e0d\u8fde\u63a5\u4e3b\u673a</p></div><nav aria-label="\u9884\u89c8\u8bbe\u7f6e"><label>\u9875\u9762<select id="page"></select></label><label>\u4e3b\u9898<select id="theme"><option value="ember">\u4f59\u70ec</option><option value="paper">\u7eb8\u767d</option><option value="ocean">\u6df1\u6d77</option><option value="iris">\u9e22\u5c3e</option><option value="forest">\u82d4\u7eff</option><option value="mono">\u58a8\u9ed1</option></select></label><label>\u52a8\u6548<select id="motion"><option value="full">\u7075\u52a8</option><option value="reduced">\u67d4\u548c</option><option value="off">\u5173\u95ed</option></select></label><label>\u5bbd\u5ea6<select id="width"><option>320</option><option>360</option><option selected>390</option><option>430</option></select></label></nav></header><main><p id="caption"></p><div class="device"><iframe id="preview" title="\u5c0f\u7a0b\u5e8f\u754c\u9762\u79bb\u7ebf\u9884\u89c8" sandbox="allow-scripts"></iframe></div></main><script>${script.replace(/<\/script/gi,'<\\/script')}</script></html>`;
fs.writeFileSync(output,text);console.log('Multi-page preview:',output);
