/* Offline native-template renderer for design QA. No networking or real operations.
 * HTML/CSS approximation, not the WeChat compiler or a native/device test.
 * Expressions executed below come ONLY from bundled developer-authored WXML.
 */
(()=>{'use strict';
 const {source,assets}=window.PREVIEW_DATA,cache={},definitions={},instances=new Map(),events=new Map(),templates={};let activeInstances=new Set();let root,route='',query={},stack=[],drawing=false,scheduled=false,nextEvent=0,clipboard='';
 const qs=new URLSearchParams(window.__PREVIEW_QUERY||location.search),desiredTheme=qs.get('theme')||'ember',themeNames=['ember','paper','ocean','iris','forest','mono'];
 function resolve(file,parent=''){const pieces=(file.startsWith('.')?parent.split('/').slice(0,-1).join('/')+'/'+file:file.replace(/^\//,'')).split('/'),out=[];for(const p of pieces){if(p==='..')out.pop();else if(p&&p!=='.')out.push(p);}let id=out.join('/');if(source[id]===undefined){if(source[id+'.js']!==undefined)id+='.js';else if(source[id+'.json']!==undefined)id+='.json';else throw Error('Missing bundled module '+id);}return id;}
 function load(file,parent){const id=resolve(file,parent);if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;if(id.endsWith('.json'))m.exports=JSON.parse(source[id]);else Function('require','module','exports',source[id])(f=>load(f,id),m,m.exports);return m.exports;}
 let capture=null;window.Page=d=>{capture=d;};window.Component=d=>{capture=d;};
 function definition(id){if(definitions[id])return definitions[id];capture=null;delete cache[id];load(id);if(!capture)throw Error('No native definition '+id);definitions[id]=capture;return capture;}
 const appearance=load('utils/appearance.js'),{Runtime}=load('services/runtime.js'),{FakeGateway}=load('services/fake-gateway.js');
 const gateway=new FakeGateway({delay:1}),rt=new Runtime(gateway),app={runtime:rt,appearance:{theme:themeNames.includes(desiredTheme)?desiredTheme:'ember',motion:'full'}};rt.auth=true;rt.live=true;rt.connection='online';rt.epoch=1;
 gateway.getProfile=async()=>({displayName:'喵连',avatarBase64:null,revision:0});gateway.user={id:'fixture_user',displayName:'喵连'};gateway.files={};gateway.counts={sessions:3,pendingRequests:2,onlineNodes:2};gateway.generation=1;gateway.ensure=async()=>{};gateway.watched={};gateway.request=async()=>{throw Error('Offline UI preview: no server requests');};gateway.list=async kind=>({items:gateway.data[kind]||[],nextPageToken:null});
 rt.command=async()=>{throw Error('Offline UI preview does not execute commands');};rt.login=async()=>{rt.auth=true;};rt.recover=async()=>{};rt.ensure=async()=>{};rt.loadTimeline=async()=>{};
 const prefs=new Map();window.getApp=()=>app;
 window.getCurrentPages=()=>stack.map(entry=>entry.page);
 const api={navigateTo:({url})=>navigate(url,'push'),redirectTo:({url})=>navigate(url,'replace'),reLaunch:({url})=>navigate(url,'reset'),switchTab:({url})=>navigate(url,'reset'),navigateBack:({delta=1}={})=>back(delta),getStorageSync:k=>prefs.get(k),setStorageSync:(k,v)=>prefs.set(k,v),setNavigationBarColor:()=>{},setBackgroundColor:()=>{},hideShareMenu:()=>{},getDeviceInfo:()=>({platform:'devtools'}),getSystemInfoSync:()=>({windowWidth:innerWidth,windowHeight:innerHeight,platform:'devtools'}),setClipboardData:({data})=>{clipboard=data;window.__preview.clipboard=data;},showToast:({title})=>{window.__preview.notice=title;},showModal:arg=>{window.__preview.modal=arg;const d=document.createElement('dialog');d.className='preview-dialog';const title=document.createElement('h3');title.textContent=arg.title;const body=document.createElement('p');body.textContent=arg.content;const dismiss=document.createElement('button');dismiss.textContent='Close preview dialog';dismiss.onclick=()=>d.remove();d.append(title,body,dismiss);document.body.append(d);d.showModal();},showActionSheet:arg=>{window.__preview.actionSheet=arg;}};
 window.wx=new Proxy(api,{get:(o,k)=>o[k]||(()=>{})});
 // Explicit fictional fixture objects, kept outside miniprogram/ production source.
 const data=gateway.data,now=Date.now();data.nodes[0].platform='macOS';data.nodes[1].platform='Linux';data.nodes[2].platform='Windows';data.projects[0].name='喵连';data.projects[0].branch='feat/refine-coding';data.projects[1].branch='main';
 for(const agent of data.agents){agent.version='local';agent.adapterVersion='1';}
 const s=data.sessions[0];s.title='\u8ba9\u4ee3\u7801\u5bf9\u8bdd\u66f4\u6709\u751f\u547d\u529b';s.agentId='demo-claude';s.state='running';s.capabilities={...data.agents[1].capabilities};s.capabilityRevision=1;s.historyState='available';s.updatedAt=now;s.queue=[];
 data.sessions[1].title='\u91cd\u6784\u65ad\u7ebf\u6062\u590d\u903b\u8f91';data.sessions[2].title='\u6574\u7406\u7f51\u5173\u4e8b\u4ef6\u6d41';
 const items=[{key:'t:1',id:'one',type:'user',text:'\u91cd\u65b0\u6253\u78e8 Coding \u9875\u9762\u3002\u5de5\u5177\u8c03\u7528\u8981\u6e05\u695a\uff0cDiff \u8981\u597d\u8bfb\uff0c\u52a8\u6548\u8981\u8f7b\u76c8\u3002',complete:true},
 {key:'t:2',id:'two',type:'assistant',text:'\u597d\u7684\u3002\u5148\u8bfb\u53d6\u73b0\u6709\u7ec4\u4ef6\uff0c\u518d\u628a\u5de5\u5177\u8c03\u7528\u548c\u4ee3\u7801\u6539\u52a8\u62c6\u6210\u6e05\u6670\u7684\u5c42\u7ea7\u3002',complete:true},
 {key:'t:3',id:'three',type:'tool',title:'Read',text:'components/event-card/index.js',detail:'export function ToolCard({ item }) {\n  return <ToolCall state={item.state} />;\n}\n\nRead 78 lines.',state:'completed'},
 {key:'t:4',id:'four',type:'diff',title:'\u66f4\u6e05\u6670\u7684\u4ee3\u7801\u53d8\u66f4',files:[{id:'fixture-diff',name:'components/tool-call.tsx',added:4,removed:2}]},
 {key:'t:5',id:'five',type:'tool',title:'Bash',text:'npm run check',detail:'Checking component boundaries...\nValidating theme tokens...\n',state:'running'}];
 rt.timelines[s.id]={items,cursor:5,pending:{},gap:null,warnings:[]};
 for(const session of data.sessions.slice(1))rt.timelines[session.id]={items:items.slice(0,2),cursor:2,pending:{},gap:null,warnings:[]};
 const patch='diff --git a/components/tool-call.tsx b/components/tool-call.tsx\n--- a/components/tool-call.tsx\n+++ b/components/tool-call.tsx\n@@ -8,6 +8,8 @@\n export function ToolCall({ item }) {\n-  const color = "#888";\n-  return <div>{item.output}</div>;\n+  const [open, setOpen] = useState(false);\n+  const running = item.state === "running";\n+  return <ToolCard active={running}\n+    expanded={open} onToggle={setOpen} />;\n }\n \n export default ToolCall;\n';
 gateway.files['fixture-diff']={id:'fixture-diff',sessionId:s.id,itemId:'four',path:'components/tool-call.tsx',language:'tsx',patch,truncated:false,createdAt:new Date(now).toISOString()};
 const share={id:'fixture-share',sessionId:s.id,title:s.title,permission:'control',createdAt:new Date(now).toISOString(),expiresAt:new Date(now+3600000).toISOString(),revokedAt:null,acceptedAt:new Date(now).toISOString(),recipientName:'\u5de5\u4f5c\u4f19\u4f34'};
 const shareLabel=load('services/shared-session.js').shareLabel;
 function construct(id,key){const def=definition(id);const obj={...def,...(def.methods||{}),definition:def,data:structuredClone(def.data||{}),key,route:id.replace(/\.js$/,''),setData(patch,cb){for(const [k,v] of Object.entries(patch)){const bits=k.split('.');let target=this.data;for(const part of bits.slice(0,-1))target=target[part]||(target[part]={});target[bits.at(-1)]=v;}if(!drawing)schedule();if(cb)cb();},triggerEvent(name,detail){const callback=this.bindings&&this.bindings[name];if(callback)callback(detail);},getTabBar(){return tab;}};for(const [k,p] of Object.entries(def.properties||{}))obj.data[k]=p&&p.value!==undefined?structuredClone(p.value):p===Boolean?false:undefined;return obj;}
 function detachAll(){for(const c of instances.values())if(c.definition.lifetimes&&c.definition.lifetimes.detached)c.definition.lifetimes.detached.call(c);instances.clear();}
 const tab=construct('custom-tab-bar/index.js','tab');

 // Navigation exercises the actual production handlers against an in-memory
 // page stack. Workspace data is a read-only fixture; writes remain blocked.
 const workspaceFixtures={
   overview:{title:'Tools',notice:'',entries:[{id:'files-menu',label:'Files',request:{kind:'files'}},{id:'attachments-menu',label:'Attachments',request:{kind:'attachments'}},{id:'tasks-menu',label:'Tasks',request:{kind:'tasks'}},{id:'account-menu',label:'Account',request:{kind:'account'}},{id:'history-menu',label:'History',request:{kind:'history'}}],controls:[]},
   files:{title:'Files',notice:'',entries:[{id:'directory-src',label:'src/',detail:'',request:{kind:'list_files',resourceId:'directory-src'}},{id:'file-readme',label:'README.md',detail:'2.4 KiB',request:{kind:'read_file',resourceId:'file-readme',format:'text'},referenceId:'file-readme'}],controls:[]},
   list_files:{title:'src/',notice:'',entries:[{id:'file-app',label:'app.js',detail:'1.8 KiB',request:{kind:'read_file',resourceId:'file-app',format:'text'},referenceId:'file-app'}],controls:[]},
   read_file:{title:'Read-only preview',notice:'',entries:[],controls:[],text:'export const workspace = {\n  title: "喵连",\n  mode: "managed"\n};'},
   attachments:{title:'Attachments',notice:'',entries:[],controls:[]},
   tasks:{title:'Tasks',notice:'',entries:[{id:'task-ui',label:'Review components',detail:'Reading component structure',state:'running',request:{kind:'task',resourceId:'task-ui'},controls:[{id:'stop-task',label:'Stop task',confirm:true,request:{kind:'stop_task',resourceId:'task-ui'},notice:'This would stop the selected task on a real host.'}]}],controls:[]},
   task:{title:'Review components',notice:'',entries:[],controls:[],text:'Read src/components\nInspect navigation and state transitions'},
   queue:{title:'Queue',notice:'',entries:[],controls:[{id:'queue-policy',label:'Queue policy',confirm:true,request:{kind:'set_queue_policy',value:'manual'},fields:[{key:'value',label:'Dispatch policy',type:'select',options:[{label:'Manual',value:'manual'},{label:'Automatic',value:'automatic'}]}]}]}
 };
 function workspace(page){
   const original=page.run;
   page.run=async function(request,resume){
     if(resume||!request||!load('utils/workspace-navigation.js').repeatable(request)){window.__preview.notice='Offline preview: writes are disabled';return;}
     const value=workspaceFixtures[request.kind]||{title:request.kind,notice:'No host connected in this preview.',entries:[],controls:[]};
     this.readRequest=structuredClone(request);
     if(load('utils/workspace-navigation.js').LABELS[request.kind])this.setData({kind:request.kind,pageTitle:load('utils/workspace-navigation.js').LABELS[request.kind]});
     this.showView({requestKind:request.kind,view:structuredClone(value)});this.refresh();
   };
   page.__nativeRun=original;page.load();
 }
 function applyIntent(){const nav=load('utils/navigation.js');const target=route==='pages/sessions/index'?'sessions':route==='pages/inbox/index'?'inbox':null;if(target){const intent=nav.consumeList(rt,target);if(intent)root.setData(Object.assign({query:''},intent));}}
 function navigate(url,mode='replace'){
   if(root&&root.onHide)root.onHide();
   const [p,q='']=url.split('?');route=p.replace(/^\//,'');query=Object.fromEntries(new URLSearchParams(q));if(!source[route+'.wxml'])throw Error('Unknown preview route '+route);
   if(mode==='reset')stack=[];else if(mode==='replace'&&stack.length)stack.pop();
   detachAll();root=construct(route+'.js','page');root.pageLife=1;stack.push({page:root,route,query});
   if(root.onLoad)root.onLoad(query);root.appearanceView();applyIntent();if(root.refresh)root.refresh();root.data.loading=false;
   if(route==='pages/workspace/index')workspace(root);
   if(route==='pages/share/index'){root.data.shares=[shareLabel(share,new Date(now).toISOString())];root.data.activity=[{id:'a',actorName:'\u5de5\u4f5c\u4f19\u4f34',actionLabel:'\u53d1\u9001\u6307\u4ee4',stateLabel:'\u5df2\u786e\u8ba4'}];}
   if(route==='pages/shared/index'&&query.id){const meta={share,session:s,ownerName:'\u5de5\u4f5c\u4f19\u4f34',agentName:'Claude Code',nodeName:'MacBook Pro',projectName:'喵连',nodeOnline:true,requests:[],serverTime:new Date(now).toISOString()};root.renderSession({meta,items,requests:{}});}
   if(route==='pages/guide/index'&&qs.has('step'))root.data.step=Number(qs.get('step'));
   window.__preview.route=route;draw();
 }
 function back(delta){
   if(stack.length<2)return navigate('/pages/home/index','reset');
   if(root.onHide)root.onHide();stack.splice(Math.max(1,stack.length-delta));const entry=stack[stack.length-1];root=entry.page;route=entry.route;query=entry.query;detachAll();root.appearanceView();if(root.refresh)root.refresh();window.__preview.route=route;draw();
 }
 function parse(text){const top={tag:'root',children:[]},stack=[top];const rx=/<!--[\s\S]*?-->|<\/?[\w-]+(?:[^"'>]|"[^"]*"|'[^']*')*>/g;let last=0,m;while((m=rx.exec(text))){if(m.index>last)stack.at(-1).children.push({text:text.slice(last,m.index)});last=rx.lastIndex;if(m[0].startsWith('<!--'))continue;if(m[0].startsWith('</')){stack.pop();continue;}const name=/^<([\w-]+)/.exec(m[0])[1],attrs={};for(const a of m[0].slice(name.length+1).replace(/\/?\s*>$/,'').matchAll(/([\w:-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'))?/g))attrs[a[1]]=a[2]??a[3]??true;const node={tag:name,attrs,children:[]};stack.at(-1).children.push(node);if(!m[0].endsWith('/>'))stack.push(node);}if(last<text.length)top.children.push({text:text.slice(last)});return top;}
 const ast=Object.fromEntries(Object.entries(source).filter(([k])=>k.endsWith('.wxml')).map(([k,v])=>[k,parse(v)]));
 for(const tree of Object.values(ast))walkTree(tree,n=>{if(n.tag==='template'&&n.attrs.name)templates[n.attrs.name]=n;});
 function walkTree(n,f){f(n);for(const c of n.children||[])walkTree(c,f);}
 function evaluate(expr,ctx){try{return Function('scope','with(scope){return ('+expr+');}')(new Proxy(ctx,{has:()=>true,get:(o,k)=>k===Symbol.unscopables?undefined:o[k]}));}catch(e){window.__preview.expressionErrors.push({expr,error:e.message});return undefined;}}
 function value(raw,ctx){if(raw===true)return true;const exact=/^\{\{((?:(?!\}\})[\s\S])*)\}\}$/.exec(raw);if(exact)return evaluate(exact[1],ctx);return String(raw).replace(/\{\{([\s\S]*?)\}\}/g,(_,e)=>evaluate(e,ctx)??'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
 const components=load('app.json').usingComponents;
 function children(nodes,ctx,owner,parent,key){let chain=false,taken=false;nodes.forEach((n,i)=>{if(n.text!==undefined){if(n.text.trim())parent.append(document.createTextNode(value(n.text,ctx)));return;}const a=n.attrs;if(a['wx:for']){const list=value(a['wx:for'],ctx)||[];for(let j=0;j<list.length;j++){const local={...ctx,[a['wx:for-item']||'item']:list[j],[a['wx:for-index']||'index']:j};const cloned={...n,attrs:{...a}};delete cloned.attrs['wx:for'];children([cloned],local,owner,parent,key+':'+i+':'+j);}chain=false;return;}
 if(a['wx:if']!==undefined){chain=true;taken=!!value(a['wx:if'],ctx);if(!taken)return;}
 else if(a['wx:elif']!==undefined){const enabled=chain&&!taken&&!!value(a['wx:elif'],ctx);taken=taken||enabled;if(!enabled)return;}
 else if(a['wx:else']!==undefined){if(!chain||taken)return;taken=true;}
 else{chain=false;taken=false;}
 if(n.tag==='import')return;if(n.tag==='template'){if(a.name)return;const template=templates[a.is];if(template){const extra=a.data?evaluate('({'+a.data.slice(2,-2)+'})',ctx):ctx;children(template.children,{...ctx,...extra},owner,parent,key+':template');}return;}
 if(n.tag==='block'){children(n.children,ctx,owner,parent,key+':'+i);return;}
 const props={};for(const [k,v] of Object.entries(a))if(!k.startsWith('wx:')&&!/^(?:bind|catch)/.test(k))props[k]=value(v,ctx);
 if(components[n.tag]){const id=components[n.tag].replace(/^\//,'')+'.js',instanceKey=key+':'+i+':'+n.tag;let c=instances.get(instanceKey);if(!c){c=construct(id,instanceKey);instances.set(instanceKey,c);}activeInstances.add(instanceKey);c.bindings={};for(const [k,handler] of Object.entries(a))if(/^(bind|catch):/.test(k))c.bindings[k.split(':')[1]]=detail=>owner[handler]({detail});
 for(const [p,v] of Object.entries(props)){const old=c.data[p];c.data[p]=v;if(c.definition.observers&&c.definition.observers[p]&&(typeof v==='object'||v!==old))c.definition.observers[p].call(c,v);}
 if(!c.__attached){c.__attached=true;if(c.definition.lifetimes&&c.definition.lifetimes.attached)c.definition.lifetimes.attached.call(c);}
 const host=document.createElement(n.tag);parent.append(host);children(ast[id.replace(/\.js$/,'.wxml')].children,c.data,c,host,instanceKey);return;}
 const map={'view':'div','text':'span','scroll-view':'div','image':'img','picker':'div','switch':'input','radio':'input','checkbox':'input','radio-group':'div','checkbox-group':'div'};const el=document.createElement(map[n.tag]||n.tag);parent.append(el);if(n.tag==='scroll-view'){el.classList.add('native-scroll');if(props['scroll-y'])el.style.overflowY='auto';if(props['scroll-x'])el.style.overflowX='auto';}
 for(const [k,v] of Object.entries(props)){if(v===undefined||v===null||k==='value')continue;if(k==='style')el.setAttribute(k,String(v).replace(/(-?\d*\.?\d+)rpx/g,(_,n)=>(Number(n)*innerWidth/750)+'px'));else if(['src'].includes(k))el.setAttribute(k,assets[v]||v);else if(k==='disabled'){el.disabled=!!v;}else if(k==='checked'){el.checked=!!v;}else if(k==='hidden'){el.hidden=!!v;}else if(['scroll-x','scroll-y','scroll-with-animation','scroll-into-view','auto-height','adjust-position','focus','enhanced'].includes(k)){}else if(k.startsWith('data-'))el.setAttribute(k,String(v));else el.setAttribute(k,String(v));}
 if(['switch','checkbox','radio'].includes(n.tag)){el.type=n.tag==='radio'?'radio':'checkbox';el.classList.add('native-toggle');}
 let pickerSelect=null;if(n.tag==='picker'){el.classList.add('native-picker');pickerSelect=document.createElement('select');pickerSelect.disabled=!!props.disabled;const range=props.range||[];range.forEach((item,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=props['range-key']?item[props['range-key']]:item;pickerSelect.append(option);});Object.defineProperty(el,'value',{get:()=>pickerSelect.value,set:value=>{pickerSelect.value=value;}});}
 if(props.value!==undefined)el.value=props.value;if(n.tag==='textarea'&&props['auto-height']){el.rows=1;el.style.resize='none';}
 for(const [binding,handler] of Object.entries(a)){if(!/^(bind|catch)/.test(binding))continue;const native=binding.replace(/^(?:bind|catch):?/,''),type=native==='tap'?'click':native==='change'?'change':native==='input'?'input':native==='focus'?'focus':native==='blur'?'blur':null;if(!type)continue;const eventID=String(++nextEvent);el.dataset.previewEvent=eventID;events.set(eventID,{owner,handler});el.addEventListener(type,e=>{if(binding.startsWith('catch'))e.stopPropagation();const dataset={};for(const [k,v] of Object.entries(props))if(k.startsWith('data-'))dataset[k.slice(5)]=v;const out=owner[handler]&&owner[handler]({currentTarget:{dataset},detail:{value:el.type==='checkbox'?el.checked:el.value},from:'button'});if(out&&out.catch)out.catch(err=>{window.__preview.notice=err.message;});schedule();});}
 children(n.children,ctx,owner,el,key+':'+i);if(pickerSelect)el.append(pickerSelect);
 });}
 function css(s,scope){s=s.replace(/:host/g,scope||':root').replace(/(-?\d*\.?\d+)rpx/g,(_,n)=>(Number(n)*innerWidth/750)+'px').replace(/(?<![\w.-])page(?=[\s{,:.#>])/g,':root').replace(/(?<![\w.-])scroll-view(?![\w-])/g,'.native-scroll').replace(/(?<![\w.-])view(?![\w-])/g,'div').replace(/(?<![\w.-])image(?![\w-])/g,'img').replace(/(?<![\w.-])text(?![\w-])/g,'span');if(scope)s=s.replace(/(^|\})(\s*)([^{}]+)\{/g,(m,end,space,selectors)=>selectors.trim().startsWith('@')||/^(from|to|[\d.,%\s]+)$/.test(selectors.trim())?m:end+space+selectors.split(',').map(v=>scope+' '+v).join(',')+'{');return s;}
 function draw(){if(!root||drawing)return;drawing=true;activeInstances=new Set();events.clear();nextEvent=0;window.__preview.expressionErrors=[];let styles=css(source['app.wxss'])+'\n'+css(source[route+'.wxss']);for(const [tag,id] of Object.entries(components))styles+='\n'+css(source[id.replace(/^\//,'')+'.wxss'],tag);styles+='\n'+css(source['custom-tab-bar/index.wxss'],'custom-tab-bar');
 styles+='\nhtml,body{margin:0;min-height:100%;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans CJK SC",sans-serif;}button,input,textarea,select{font-family:inherit;}.native-picker{position:relative;}.native-picker>select{position:absolute;inset:0;opacity:0;width:100%;height:100%;cursor:pointer;}button{cursor:pointer;}span{box-sizing:border-box;}img{object-fit:contain;}input[type=checkbox],input[type=radio]{width:20px;height:20px;min-height:0;padding:0;}'+Object.keys(components).concat(['custom-tab-bar']).join(',')+'{display:block;}ui-icon{display:inline-flex;flex:none;align-items:center;justify-content:center;vertical-align:middle;line-height:0;}button[size=mini]{vertical-align:middle;}textarea{outline:none;}dialog.preview-dialog{max-width:85%;background:#20211e;color:#f2f1e8;border:1px solid #393d32;border-radius:20px;}dialog::backdrop{background:#0009;}';document.querySelector('#styles').textContent=styles;const target=document.querySelector('#app');target.replaceChildren();children(ast[route+'.wxml'].children,root.data,root,target,'page');if(['pages/home/index','pages/sessions/index','pages/inbox/index','pages/me/index'].includes(route)){const host=document.createElement('custom-tab-bar');target.append(host);tab.data={...tab.data,...appearance.view(app.appearance),selected:['pages/home/index','pages/sessions/index','pages/inbox/index','pages/me/index'].indexOf(route)};children(ast['custom-tab-bar/index.wxml'].children,tab.data,tab,host,'tab');}for(const [key,c] of instances){if(!activeInstances.has(key)){if(c.definition.lifetimes&&c.definition.lifetimes.detached)c.definition.lifetimes.detached.call(c);instances.delete(key);}}drawing=false;window.__preview.ready=true;}
 function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;draw();});}
 window.__preview={ready:false,expressionErrors:[],notice:'',clipboard,navigate,back,runtime:rt,stack:()=>stack.map(e=>({route:e.route,id:e.page.data.id})),root:()=>root,instances:()=>instances,setTheme(id){appearance.set(app,wx,{theme:id});root.appearanceView();draw();},setMotion(id){appearance.set(app,wx,{motion:id});root.appearanceView();draw();},showThemes(){root.showThemes();draw();},fixture:true};
 const page=qs.get('page')||'session',defaults={session:{id:s.id},share:{id:s.id},shared:{id:share.id},panel:{sessionId:s.id,kind:'diff',itemKey:'t:4'},file:{sessionId:s.id,fileId:'fixture-diff'},request:{id:'demo-input'},node:{id:'demo-mac'},project:{id:'demo-web'},agent:{id:'demo-claude'},requirement:{id:load('catalog/requirements.js')[0].id},workspace:{id:s.id,kind:qs.get('kind')||'overview'}};
 navigate('/pages/'+page+'/index?'+new URLSearchParams(defaults[page]||{}));
})();
