"""Interaction regression for the bundled WXML/WXSS browser approximation.
No network calls, native WeChat rendering, credentials, or host execution.
"""
from pathlib import Path
import argparse,json
from playwright.sync_api import sync_playwright
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--html',type=Path,required=True)
parser.add_argument('--output',type=Path,required=True)
parser.add_argument('--chromium',default=None)
args=parser.parse_args();args.output.mkdir(parents=True,exist_ok=True)
html=args.html.read_text();checks=[]
def check(name,value,detail=None):
    checks.append({'name':name,'passed':bool(value),'detail':detail})
    if not value:print('FAIL',name,detail)
def content(query):return html.replace('<head>','<head><script>window.__PREVIEW_QUERY='+json.dumps(query)+';</script>',1)
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=args.chromium,headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
    page=browser.new_page(viewport={'width':390,'height':844},device_scale_factor=2)
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    def show(name,theme='ember',kind=None):
        page.set_content(content('?page='+name+'&theme='+theme+('&kind='+kind if kind else '')))
        page.wait_for_function('window.__preview && window.__preview.ready');page.wait_for_timeout(70)
    def state():return page.evaluate('window.__preview.root().data')
    def snap(name,full=True):
        page.wait_for_timeout(250);page.screenshot(path=str(args.output/(name+'.png')),full_page=full)
    show('home');page.locator('.metric-tile').first.click();page.wait_for_timeout(80)
    check('overview active shortcut routes to filtered sessions',state()['filter']=='active')
    check('shortcut clears unrelated scopes',state()['scopeCount']==0)
    show('sessions','paper');page.locator('.scope-trigger').click();page.locator('.flow-sheet select').first.select_option('1');page.wait_for_timeout(60)
    check('filter stays staged until Apply',state()['scopeCount']==0)
    page.locator('.sheet-close').click();check('dismiss leaves original filter',state()['nodeId']=='')
    page.locator('.scope-trigger').click();page.locator('.flow-sheet select').first.select_option('1');page.wait_for_timeout(60);page.locator('.sheet-actions .primary').click();page.wait_for_timeout(100)
    check('filter applies exact directory identity',state()['nodeId']=='demo-mac')
    check('filter result stays within exact host',all(s['nodeId']=='demo-mac' for s in state()['list']))
    snap('sessions-paper')
    show('session');page.evaluate('window.__preview.root().input({detail:{value:"Preserve this draft"}})');page.wait_for_timeout(70)
    page.locator('.more').click();page.wait_for_timeout(100)
    check('Coding menu is local',page.evaluate('window.__preview.route')=='pages/session/index')
    check('menu groups visible',page.locator('.sheet-group-title').count()==3)
    snap('coding-menu-ember',False)
    page.locator('.menu-grid [data-kind="input"]').click();page.wait_for_timeout(100)
    check('attachments opens exact session',state()['kind']=='attachments' and state()['id']=='demo-review')
    check('unrelated organization controls absent',page.locator('[data-key="metadataTitle"]').count()==0)
    check('attachment selection stays explicit',page.locator('[bindtap]').count()==0 and page.get_by_role('button',name='\u56fe\u7247',exact=True).count()==1 and page.get_by_role('button',name='\u6587\u4ef6',exact=True).count()==1)
    page.locator('.breadcrumb').click();page.wait_for_timeout(100)
    check('returns to original Coding stack entry',page.evaluate('window.__preview.stack().length')==1)
    check('return preserves composer draft',state()['draft']=='Preserve this draft')
    page.locator('.more').click();page.wait_for_timeout(70);page.locator('.menu-grid [data-kind="organization"]').click();page.wait_for_timeout(100)
    check('organization isolated into dedicated screen',state()['kind']=='organization' and page.locator('[data-key="metadataTitle"]').count()==1)
    check('organization does not call a native operation',state()['view'] is None)
    snap('organization-ember')
    show('workspace','paper','files');page.locator('[data-id="directory-src"]').click();page.wait_for_timeout(100)
    check('directory drilldown uses returned identifier',page.evaluate('window.__preview.root().readRequest.resourceId')=='directory-src')
    page.locator('[data-id="file-app"]').filter(has_text='\u6253\u5f00').click();page.wait_for_timeout(100)
    check('opens read-only text',page.locator('.file-text').count()==1)
    page.locator('[aria-label="\u5237\u65b0"]').click();page.wait_for_timeout(70)
    check('refresh stays on exact opened file',page.evaluate('window.__preview.root().readRequest.resourceId')=='file-app')
    show('workspace','ocean','tasks');page.locator('[data-id="stop-a"]').count()
    check('entry control is adjacent to its task',page.locator('.workspace-entry .control-panel').count()==1)
    page.locator('.control-panel .row-button').click();page.wait_for_timeout(70)
    check('control expands without sending',page.locator('.control-body').count()==1 and page.locator('dialog').count()==0)
    snap('tasks-ocean')
    show('project')
    geometry=page.locator('.actions button').evaluate_all('(els)=>els.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}))')
    check('project primary and secondary actions remain usable side by side',len(geometry)==2 and all(e['w']>=120 and e['h']<=64 for e in geometry),geometry)
    page.locator('[data-kind="files"]').click();page.wait_for_timeout(70)
    check('multi-session project opens selector',state().get('toolPicker') is True)
    check('selector lists only project members',all(s['projectId']=='demo-web' for s in state()['toolSessions']))
    snap('project-session-picker')
    page.locator('session-picker .context-option').first.click();page.wait_for_timeout(90)
    check('project file navigation has session context',page.evaluate('window.__preview.route')=='pages/workspace/index' and bool(state()['id']))
    show('agent');page.locator('button.primary').click();page.wait_for_timeout(90)
    check('new-session route preserves Agent choice',page.evaluate('window.__preview.route')=='pages/create/index' and state()['agentId']=='demo-claude')
    check('new-session choice resolves correct host',state()['nodeId']=='demo-mac')
    check('preview preserves native text-align declarations',page.locator('.agent-option .grow').first.evaluate('(e)=>getComputedStyle(e).textAlign')=='left')
    page.locator('.task-input textarea').fill('Keep this task');page.wait_for_timeout(70)
    # Selection handlers are real; the fixture renderer maps picker to HTML select.
    page.locator('.environment select').first.select_option('1');page.wait_for_timeout(70)
    check('changing host preserves task draft',state()['prompt']=='Keep this task')
    show('inbox');page.locator('[data-value="notices"]').click();page.wait_for_timeout(70)
    check('notification tab uses notification list',state()['filter']=='notices')
    check('no placeholder question-mark labels', '????????' not in page.inner_text('body'))
    show('session');page.evaluate('window.__preview.root().dragStart({detail:{scrollTop:400}});window.__preview.root().dragging({detail:{scrollTop:300}})');page.wait_for_timeout(60)
    check('upward drag exposes jump to latest',page.locator('.jump').count()==1)
    page.locator('.jump').click();page.wait_for_timeout(60);check('explicit jump resumes following',state()['following'])
    # Non-empty secondary screens, all palettes and a narrow viewport.
    for theme in ['ember','paper','ocean','iris','forest','mono']:
        for name,kind in [('home',None),('nodes',None),('node',None),('projects',None),('project',None),('agent',None),('create',None),('inbox',None),('me',None),('workspace','overview'),('workspace','attachments'),('workspace','organization')]:
            page.set_viewport_size({'width':320,'height':740});show(name,theme,kind)
            expression_errors=page.evaluate('window.__preview.expressionErrors')
            check(f'{name}/{kind or "root"} {theme} nonempty render',not expression_errors and page.evaluate('document.body.scrollWidth')<=320,expression_errors[:2])
            if name=='project':
                check(f'project {theme} narrow action sizing',page.locator('.actions button').evaluate_all('(els)=>els.every(e=>e.getBoundingClientRect().width>=100 && e.getBoundingClientRect().height<=60)'))
    page.set_viewport_size({'width':390,'height':844})
    for name,theme,kind in [('home','ember',None),('nodes','paper',None),('node','ember',None),('projects','ocean',None),('project','paper',None),('agent','iris',None),('create','ember',None),('inbox','ember',None),('me','paper',None),('workspace','ocean','overview'),('workspace','paper','attachments')]:
        show(name,theme,kind);snap(name+'-'+(kind+'-' if kind else '')+theme)
    check('no uncaught browser errors',not errors,errors)
    browser.close()
result={'mode':'Offline WXML/WXSS HTML approximation. Actual page event handlers; isolated fixtures, not native WeChat/device/Gateway acceptance.','passed':sum(c['passed'] for c in checks),'failed':sum(not c['passed'] for c in checks),'checks':checks}
(args.output/'qa-flow-report.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
print('CHECKS',len(checks),'PASS',result['passed'],'FAIL',result['failed'])
if result['failed']:raise SystemExit(1)
